mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib',
  :tag => 'v2.2.1'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :tag => '1.8.0'

mod 'wget',
  :git => 'https://github.com/maestrodev/puppet-wget.git',
  :tag => 'v1.5.7'